### ISSUE TITLE
macOS Catalina10.15 浏览器登录失败

### ISSUE THREAD

**Issue by kezade** [HuLaSpark/HuLa#8]
启动登录界面后，登录失败。报错如下：
`chunk-C4ADJDYZ.js?v=4a2adac9:30 Uncaught (in promise) 
TypeError: window.__TAURI_IPC__ is not a function
    at chunk-C4ADJDYZ.js?v=4a2adac9:30:12
    at new Promise (<anonymous>)
    at invoke (chunk-C4ADJDYZ.js?v=4a2adac9:21:10)
    at invokeTauriCommand (chunk-O5WPOBGQ.js?v=4a2adac9:7:10)
    at listen (chunk-3D25F3FL.js?v=4a2adac9:31:10)
    at listen2 (chunk-3D25F3FL.js?v=4a2adac9:74:10)
    at ActionBar.vue:133:3
    at callWithErrorHandling (chunk-UXUYPSZY.js?v=4a2adac9:1663:19)
    at callWithAsyncErrorHandling (chunk-UXUYPSZY.js?v=4a2adac9:1670:17)
    at ReactiveEffect.getter [as fn] (chunk-UXUYPSZY.js?v=4a2adac9:7495:16)
chunk-C4ADJDYZ.js?v=4a2adac9:30 Uncaught (in promise) 
TypeError: window.__TAURI_IPC__ is not a function
    at chunk-C4ADJDYZ.js?v=4a2adac9:30:12
    at new Promise (<anonymous>)
    at invoke (chunk-C4ADJDYZ.js?v=4a2adac9:21:10)
    at invokeTauriCommand (chunk-O5WPOBGQ.js?v=4a2adac9:7:10)
    at listen (chunk-3D25F3FL.js?v=4a2adac9:31:10)
    at listen2 (chunk-3D25F3FL.js?v=4a2adac9:74:10)
    at ActionBar.vue:139:3
    at callWithErrorHandling (chunk-UXUYPSZY.js?v=4a2adac9:1663:19)
    at callWithAsyncErrorHandling (chunk-UXUYPSZY.js?v=4a2adac9:1670:17)
    at ReactiveEffect.getter [as fn] (chunk-UXUYPSZY.js?v=4a2adac9:7495:16)`

**Comment by kezade** [comment]
![image](https://github.com/user-attachments/assets/3deb849c-5d51-4c15-a45f-8ff6ccf2bca5)
截图如上

**Comment by nongyehong** [comment]
英特尔的芯片版本的mac是吗？

**Comment by kezade** [comment]
> 英特尔的芯片版本的mac是吗？

是的

**Comment by nongyehong** [comment]
项目下打开控制台输入tauri info我看一下信息

**Comment by nongyehong** [comment]
英特尔版本tauri v2似乎有问题，待官方修复后可重新开启此议题

**Comment by nongyehong** [comment]
请下载或更新最新版本的代码
